const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const routes = fs.readFileSync(path.join(root, 'src/app/app.routes.ts'), 'utf8');
const detail = fs.readFileSync(path.join(root, 'src/app/features/course-detail/course-detail.ts'), 'utf8');
const layout3 = fs.readFileSync(path.join(root, 'src/app/features/layout-style-3/layout-style-3.ts'), 'utf8');
const layout3Template = fs.readFileSync(path.join(root, 'src/app/features/layout-style-3/layout-style-3.html'), 'utf8');
const layout3Styles = fs.readFileSync(path.join(root, 'src/app/features/layout-style-3/layout-style-3.scss'), 'utf8');
const detailTemplate = fs.readFileSync(path.join(root, 'src/app/features/course-detail/course-detail.html'), 'utf8');
const models = fs.readFileSync(path.join(root, 'src/app/core/models.ts'), 'utf8');
const detailStyles = fs.readFileSync(path.join(root, 'src/app/features/course-detail/course-detail.scss'), 'utf8');

assert.match(routes, /\{ path: '', component: LayoutStyle3Page \}/);
assert.doesNotMatch(routes, /AnimationStyle2Page|animation-style-2/);
assert.match(detail, /this\.router\.navigate\(\['\/layout-style-3'\]/);
assert.doesNotMatch(detail, /this\.router\.navigate\(\['\/animation-style-2'\]/);
assert.doesNotMatch(detail, /this\.location\.back\(\)/);
assert.match(layout3, /'catalog',\s*\{/);
assert.doesNotMatch(layout3, /'style-2',\s*\{/);
assert.match(models, /title_image\?:?\s*string \| null/);
assert.match(layout3Template, /title_image/);
assert.match(detailTemplate, /title_image/);
assert.match(detail, /if \(course\.course_types\.includes\('Shows'\)\) return 'Show';/);
assert.match(detailStyles, /\.detail__hero[\s\S]*align-items: flex-start;/);
assert.match(detailStyles, /\.detail__hero[\s\S]*padding: 300px /);
assert.match(detailStyles, /\.detail__body[\s\S]*margin-top: calc\(-92vh \+ 300px\);/);
assert.match(detailStyles, /rgba\(11, 13, 12, 0\.4\) 879px,[\s\S]*transparent 1521px/);
assert.match(detailStyles, /rgba\(11, 13, 12, 1\) 0px,[\s\S]*rgba\(11, 13, 12, 0\.4\) 879px/);
assert.match(layout3Template, /class="style-featured__background"[\s\S]*class="style-featured__background-link"[\s\S]*openCourse\(course, \$event\)/);
assert.match(layout3Template, /class="style-featured__background-link"[\s\S]*\[attr\.aria-label\]="'Open featured/);
assert.doesNotMatch(layout3Template, /<p class="style-page__eyebrow">\{\{ featuredLabel\(course\) \}\}<\/p>/);
assert.match(layout3Styles, /\.style-featured__background-link[\s\S]*background: transparent !important;/);
assert.match(layout3Styles, /\.style-page \.style-featured__background-link:hover[\s\S]*background: transparent !important;/);
assert.match(detailTemplate, /<div class="detail__description"[\s\S]*<div class="detail__meta">[\s\S]*<\/div>/);
const metaBlock = detailTemplate.match(/<div class="detail__meta">([\s\S]*?)<\/div>/)?.[1] ?? '';
assert.doesNotMatch(metaBlock, /detail__overview-btn/);
assert.match(detailTemplate, /@if \(c\.course_types\.includes\('Shows'\) && c\.characters\?\.length\)/);
assert.match(detailTemplate, /detail__characters[\s\S]*c\.characters/);
assert.match(detailStyles, /\.detail__characters[\s\S]*margin-top: 20px;/);
assert.match(detailStyles, /\.detail__instructor-label,[\s\S]*\.detail__characters-label[\s\S]*font-weight: 600;/);
assert.match(detailStyles, /\.detail__instructor-name[\s\S]*font-weight: 600;/);
assert.match(detailStyles, /\.detail__instructor-name[\s\S]*color: #F2F0E8;/);
assert.match(layout3Template, /style-featured__people-row[\s\S]*detail\.instructor[\s\S]*detail\.guest/);
assert.match(detailTemplate, /detail__people-row[\s\S]*c\.instructor[\s\S]*c\.guest/);
assert.match(detailStyles, /\.detail__people-row[\s\S]*display: flex;/);
assert.match(layout3Styles, /\.style-featured__people-row[\s\S]*display: flex;/);
assert.match(layout3Styles, /\.style-featured__people-row \.style-featured__person-avatar[\s\S]*width: 41px;[\s\S]*height: 41px;/);
assert.match(layout3Styles, /\.style-featured__person-label[\s\S]*font-weight: 600;/);
assert.match(layout3Styles, /\.style-featured__person-row[\s\S]*font-weight: 600;/);
assert.match(layout3Styles, /\.style-featured__character span[\s\S]*font-weight: 600;/);
assert.match(layout3Styles, /\.style-featured__person-row[\s\S]*color: #F2F0E8;/);
assert.match(layout3Styles, /\.style-course-modal__person-row[\s\S]*color: #F2F0E8;/);
assert.match(layout3Styles, /\.lesson-list--revealed \.lesson-row[\s\S]*transition: transform 0\.18s ease-in, background-color 0\.18s ease-in;/);
assert.match(layout3Styles, /\.style-course-modal__lesson[\s\S]*transition: transform 0\.18s ease/);
assert.match(layout3Styles, /\.style-course-modal__lesson:hover[\s\S]*transform: scale\(/);
assert.match(layout3Styles, /\.episode-panel__header[\s\S]*margin-bottom: 0\.5rem;[\s\S]*padding: 3px 8px 9px;[\s\S]*border-radius: var\(--button-radius\);[\s\S]*background: rgba\(12, 13, 13, 0\.7\);/);
assert.match(detailStyles, /\.lesson-list--revealed \.lesson-row[\s\S]*transition: transform 0\.18s ease-out, background-color 0\.18s ease-in;/);
assert.match(detailStyles, /\.detail__lessons-title[\s\S]*margin-bottom: 0\.5rem;[\s\S]*padding: 3px 8px 9px;[\s\S]*border-radius: var\(--button-radius\);[\s\S]*background: rgba\(12, 13, 13, 0\.7\);/);
assert.match(detailStyles, /\.detail__back-icon[\s\S]*background: transparent;/);
assert.match(detailStyles, /\.detail__back-icon[\s\S]*border: none;/);
assert.match(detailStyles, /\.detail__back-icon[\s\S]*width: 18px;/);
assert.match(detailStyles, /\.detail__back-icon[\s\S]*height: 18px;/);
assert.match(detailStyles, /\.detail__back[\s\S]*font-family: 'Inter', sans-serif;/);
assert.match(detailStyles, /\.detail__back[\s\S]*font-weight: 600;/);
assert.match(detailStyles, /\.detail__back[\s\S]*background: #33373D;/);
assert.match(detailStyles, /\.detail__back[\s\S]*background: #fff;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*background: #33373D;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*background: #fff;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*border: none;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*font-family: 'Inter', sans-serif;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*font-weight: 600;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*background: #33373D;/);
assert.match(detailStyles, /\.detail__overview-btn[\s\S]*background: #fff;/);

console.log('layout 3 standard contract passes');
