const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const template = fs.readFileSync(path.join(root, 'src/app/features/catalog/course-catalog.html'), 'utf8');
const component = fs.readFileSync(path.join(root, 'src/app/features/catalog/course-catalog.ts'), 'utf8');
const homeTemplate = fs.readFileSync(path.join(root, 'src/app/features/animation-style-2/animation-style-2.html'), 'utf8');
const homeComponent = fs.readFileSync(path.join(root, 'src/app/features/animation-style-2/animation-style-2.ts'), 'utf8');
const service = fs.readFileSync(path.join(root, 'src/app/core/courses.service.ts'), 'utf8');
const api = fs.readFileSync(path.join(root, '../wordpress-plugin/tcnexus-lms/includes/class-tcnexus-rest-api.php'), 'utf8');
const builder = fs.readFileSync(path.join(root, '../wordpress-plugin/tcnexus-lms/includes/class-tcnexus-course-builder.php'), 'utf8');

assert.match(template, /shows\(\)/);
assert.match(template, /data-row-title="Shows"/);
assert.match(component, /getShows\(\)/);
assert.match(component, /protected readonly shows/);
assert.match(homeTemplate, /id="shows-title"/);
assert.match(homeTemplate, /#showsTrack/);
assert.match(homeTemplate, /scroll\(-1, 'shows'\)/);
assert.match(homeTemplate, /\{\{ featuredLabel\(course\) \}\}/);
assert.match(homeTemplate, /style-row--trading/);
assert.match(homeTemplate, /isShow\(course\) \? 'episodes' : 'lessons'/);
assert.match(homeTemplate, /isShow\(course\) \? 'Episode List' : 'Lessons List'/);
assert.match(homeTemplate, /@if \(!isShow\(course\)\)/);
assert.match(homeTemplate, /\{\{ show\.lesson_count \}\} episodes/);
assert.match(homeComponent, /getShows\(\)/);
assert.match(homeComponent, /type CarouselKind = 'shows'/);
assert.match(homeComponent, /const available = \[\.\.\.courseCandidates, \.\.\.showCandidates\]/);
assert.match(homeComponent, /course\.course_types\.includes\('Shows'\)/);
assert.match(homeComponent, /STYLE2_FEATURED_KIND_STORAGE_KEY/);
assert.match(homeComponent, /const savedFeaturedId = this\.pendingReturn\?\.style2State\?\.featuredId \?\? queryFeaturedId/);
assert.match(homeComponent, /Demo Show 01/);
assert.match(homeComponent, /Demo Show 04/);
assert.match(service, /getShows\(\)/);
assert.match(service, /\/shows/);
assert.match(service, /the-primer-episode-1\.m4v/);
assert.match(service, /38201/);
assert.match(homeTemplate, /trailerVideoUrl\(\)/);
assert.match(api, /register_rest_route\( self::NAMESPACE_, '\/shows'/);
assert.match(builder, /<b>Characters:<\/b>/);
assert.match(builder, /SHOW_CHARACTERS_META_KEY/);
assert.match(builder, /data-character-picker="1"/);
assert.match(builder, /Selected Characters/);
assert.match(builder, /'people' => self::is_show_mode\(\) \? 'Characters' : 'People'/);
const builderJs = fs.readFileSync(path.join(root, '../wordpress-plugin/tcnexus-lms/assets/course-builder.js'), 'utf8');
const media = fs.readFileSync(path.join(root, '../wordpress-plugin/tcnexus-lms/includes/class-tcnexus-media.php'), 'utf8');
assert.match(builderJs, /option\.disabled = true/);
assert.match(builderJs, /option\.disabled = false/);
assert.match(builder, /class="tcn-save-confirmation"/);
assert.match(builder, /name="active_tab"/);
assert.match(builder, /\$return_tab/);
assert.match(builderJs, /activeTabInput\.value/);
assert.match(media, /'fallback' => true/);

console.log('shows carousel contract passes');
