const assert = require('node:assert/strict');
const fs = require('node:fs');

const php = fs.readFileSync('wordpress-plugin/tcnexus-lms/includes/class-tcnexus-admin-menu.php', 'utf8');
const js = fs.readFileSync('wordpress-plugin/tcnexus-lms/assets/media-library.js', 'utf8');
const css = fs.readFileSync('wordpress-plugin/tcnexus-lms/assets/media-library-interactions.css', 'utf8');
const pageCss = fs.readFileSync('wordpress-plugin/tcnexus-lms/assets/media-library-bulk.css', 'utf8');
const plugin = fs.readFileSync('wordpress-plugin/tcnexus-lms/tcnexus-lms.php', 'utf8');

assert.match(php, /ajax_move_media/);
assert.match(php, /ajax_media_details/);
assert.match(php, /ajax_delete_media/);
assert.match(php, /ajax_bulk_delete_media/);
assert.match(php, /ajax_upload_media/);
assert.match(plugin, /wp_ajax_tcnexus_media_library_bulk_delete/);
assert.match(plugin, /wp_ajax_tcnexus_media_library_upload/);
assert.match(php, /wp_delete_attachment/);
assert.match(js, /dragover/);
assert.match(js, /drop/);
assert.match(js, /details/);
assert.match(js, /delete/);
assert.match(js, /tcn-media-library-item__delete/);
assert.match(js, /viewBox="0 0 24 24"/);
assert.match(js, /copy/);
assert.match(js, /File URL/);
assert.match(css, /details/);
assert.match(css, /translateY\(-1px\)/);
assert.match(css, /delete/);
assert.match(js, /tcnexus_media_library_bulk_delete/);
assert.match(js, /type = 'file'/);
assert.match(js, /FormData/);
assert.doesNotMatch(js, /wp\.media/);
assert.match(pageCss, /tcn-media-library-upload[\s\S]*#5fc7a8/);
assert.match(pageCss, /tcn-media-library-upload\{height:36px!important/);
assert.match(pageCss, /tcn-media-library-bulk/);
assert.match(pageCss, /tcn-media-library-item__select\{display:none!important/);
assert.match(php, /wp_get_attachment_url/);
assert.match(php, /wp_get_attachment_url/);

console.log('media library interactions contract passes');
